theme: jekyll-theme-leap-day
title: Welcome to the homepage
description: I post my solutions to the real number game to help me and others learn to use lean. There''s a future project where people post solutions and rate them.
